### ISSUE TITLE
Featured posts

### ISSUE THREAD

**Issue by ShalokShalom** [RustPython/rustpython.github.io#38]
Hi :)

I detected a misleading link and come here, to correct it in code.

Can you tell me, where to find this featured posts section?

![Screenshot_2021-03-24-11-33-08-49](https://user-images.githubusercontent.com/6344099/112295978-bbe00000-8c94-11eb-8e05-74c7355959d1.jpg)

The pip post leads straight to the homepage, I like to switch it with ~~https://rustpython.github.io/~~ 
https://rustpython.github.io/featured/2021/01/26/pip-support.html

**Comment by youknowone** [comment]
Hi, thank you for looking for the correct article. :joy: The article is here: https://rustpython.github.io/featured/2021/01/26/pip-support.html

**Comment by ShalokShalom** [comment]
I know where the correct article is. I am looking for the correct place in this repository, to switch the code :smile:

**Comment by coolreader18** [comment]
Oh, I think you need to add a `permalink` attribute to the pip-support post: the [other featured post](https://github.com/RustPython/rustpython.github.io/blob/master/_posts/2020-04-05-how-to-contribute-by-cpython-unittest.markdown) has a `permalink: ` in its yaml front matter, and I think you just need to mirror that for the [pip one](https://github.com/RustPython/rustpython.github.io/blob/master/_posts/2021-01-27-pip-support.markdown). @mireille-raad is there a way to automate getting the permalink to a post so that we don't have to remember to do it manually?

**Comment by coolreader18** [comment]
Actually @ShalokShalom, try swapping out `post.permalink` [in the home layout](https://github.com/RustPython/rustpython.github.io/blob/bf2f4b0bf4b2d1da7ecc8b96282be292ae2a21cb/_layouts/home.html#L118-L124) with `post.url`, I think that should fix it systemically
